[package]
name = "desky"
version = "0.1.0"
description = "A Tauri App"
authors = ["youtube@iaiuse.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
tauri = { version = "1.0.0", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
